import Head from 'next/head'
import { GlobalStyle } from './api/StyledComponents'
import Blender from './Blender'
import Header from './Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Jwplayer Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Blender />
      </main>
    </div>
  )
}
